// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package client

import (
	"context"
	"net/http"

	"github.com/Yamashou/gqlgenc/client"
	generated "github.com/winwisely268/sanfood-faker/model"
)

type Client struct {
	Client *client.Client
}

func NewClient(cli *http.Client, baseURL string, options ...client.HTTPRequestOption) *Client {
	return &Client{Client: client.NewClient(cli, baseURL, options...)}
}

type QueryRoot struct {
	Accounts                         []*generated.Accounts                     "json:\"accounts\" graphql:\"accounts\""
	AccountsAggregate                generated.AccountsAggregate               "json:\"accounts_aggregate\" graphql:\"accounts_aggregate\""
	AccountsByPk                     *generated.Accounts                       "json:\"accounts_by_pk\" graphql:\"accounts_by_pk\""
	AttendanceConfig                 []*generated.AttendanceConfig             "json:\"attendance_config\" graphql:\"attendance_config\""
	AttendanceConfigAggregate        generated.AttendanceConfigAggregate       "json:\"attendance_config_aggregate\" graphql:\"attendance_config_aggregate\""
	AttendanceConfigByPk             *generated.AttendanceConfig               "json:\"attendance_config_by_pk\" graphql:\"attendance_config_by_pk\""
	AttendanceRecords                []*generated.AttendanceRecords            "json:\"attendance_records\" graphql:\"attendance_records\""
	AttendanceRecordsAggregate       generated.AttendanceRecordsAggregate      "json:\"attendance_records_aggregate\" graphql:\"attendance_records_aggregate\""
	AttendanceRecordsByPk            *generated.AttendanceRecords              "json:\"attendance_records_by_pk\" graphql:\"attendance_records_by_pk\""
	Branches                         []*generated.Branches                     "json:\"branches\" graphql:\"branches\""
	BranchesAggregate                generated.BranchesAggregate               "json:\"branches_aggregate\" graphql:\"branches_aggregate\""
	BranchesByPk                     *generated.Branches                       "json:\"branches_by_pk\" graphql:\"branches_by_pk\""
	Contracts                        []*generated.Contracts                    "json:\"contracts\" graphql:\"contracts\""
	ContractsAggregate               generated.ContractsAggregate              "json:\"contracts_aggregate\" graphql:\"contracts_aggregate\""
	ContractsByPk                    *generated.Contracts                      "json:\"contracts_by_pk\" graphql:\"contracts_by_pk\""
	Distributors                     []*generated.Distributors                 "json:\"distributors\" graphql:\"distributors\""
	DistributorsAggregate            generated.DistributorsAggregate           "json:\"distributors_aggregate\" graphql:\"distributors_aggregate\""
	DistributorsByPk                 *generated.Distributors                   "json:\"distributors_by_pk\" graphql:\"distributors_by_pk\""
	DistroStoreAssignments           []*generated.DistroStoreAssignments       "json:\"distro_store_assignments\" graphql:\"distro_store_assignments\""
	DistroStoreAssignmentsAggregate  generated.DistroStoreAssignmentsAggregate "json:\"distro_store_assignments_aggregate\" graphql:\"distro_store_assignments_aggregate\""
	DistroStoreAssignmentsByPk       *generated.DistroStoreAssignments         "json:\"distro_store_assignments_by_pk\" graphql:\"distro_store_assignments_by_pk\""
	GetSessionRole                   []*generated.TextResult                   "json:\"get_session_role\" graphql:\"get_session_role\""
	GetSessionRoleAggregate          generated.TextResultAggregate             "json:\"get_session_role_aggregate\" graphql:\"get_session_role_aggregate\""
	Inventories                      []*generated.Inventories                  "json:\"inventories\" graphql:\"inventories\""
	InventoriesAggregate             generated.InventoriesAggregate            "json:\"inventories_aggregate\" graphql:\"inventories_aggregate\""
	InventoriesByPk                  *generated.Inventories                    "json:\"inventories_by_pk\" graphql:\"inventories_by_pk\""
	Locations                        []*generated.Locations                    "json:\"locations\" graphql:\"locations\""
	LocationsAggregate               generated.LocationsAggregate              "json:\"locations_aggregate\" graphql:\"locations_aggregate\""
	LocationsByPk                    *generated.Locations                      "json:\"locations_by_pk\" graphql:\"locations_by_pk\""
	MarketingRegions                 []*generated.MarketingRegions             "json:\"marketing_regions\" graphql:\"marketing_regions\""
	MarketingRegionsAggregate        generated.MarketingRegionsAggregate       "json:\"marketing_regions_aggregate\" graphql:\"marketing_regions_aggregate\""
	MarketingRegionsByPk             *generated.MarketingRegions               "json:\"marketing_regions_by_pk\" graphql:\"marketing_regions_by_pk\""
	MateStores                       []*generated.MateStores                   "json:\"mate_stores\" graphql:\"mate_stores\""
	MateStoresAggregate              generated.MateStoresAggregate             "json:\"mate_stores_aggregate\" graphql:\"mate_stores_aggregate\""
	MateStoresByPk                   *generated.MateStores                     "json:\"mate_stores_by_pk\" graphql:\"mate_stores_by_pk\""
	ProductCategories                []*generated.ProductCategories            "json:\"product_categories\" graphql:\"product_categories\""
	ProductCategoriesAggregate       generated.ProductCategoriesAggregate      "json:\"product_categories_aggregate\" graphql:\"product_categories_aggregate\""
	ProductCategoriesByPk            *generated.ProductCategories              "json:\"product_categories_by_pk\" graphql:\"product_categories_by_pk\""
	ProductPackagings                []*generated.ProductPackagings            "json:\"product_packagings\" graphql:\"product_packagings\""
	ProductPackagingsAggregate       generated.ProductPackagingsAggregate      "json:\"product_packagings_aggregate\" graphql:\"product_packagings_aggregate\""
	ProductPackagingsByPk            *generated.ProductPackagings              "json:\"product_packagings_by_pk\" graphql:\"product_packagings_by_pk\""
	ProductPictures                  []*generated.ProductPictures              "json:\"product_pictures\" graphql:\"product_pictures\""
	ProductPicturesAggregate         generated.ProductPicturesAggregate        "json:\"product_pictures_aggregate\" graphql:\"product_pictures_aggregate\""
	ProductPicturesByPk              *generated.ProductPictures                "json:\"product_pictures_by_pk\" graphql:\"product_pictures_by_pk\""
	Products                         []*generated.Products                     "json:\"products\" graphql:\"products\""
	ProductsAggregate                generated.ProductsAggregate               "json:\"products_aggregate\" graphql:\"products_aggregate\""
	ProductsByPk                     *generated.Products                       "json:\"products_by_pk\" graphql:\"products_by_pk\""
	SearchProductCategories          []*generated.ProductCategories            "json:\"search_product_categories\" graphql:\"search_product_categories\""
	SearchProductCategoriesAggregate generated.ProductCategoriesAggregate      "json:\"search_product_categories_aggregate\" graphql:\"search_product_categories_aggregate\""
	SearchProducts                   []*generated.Products                     "json:\"search_products\" graphql:\"search_products\""
	SearchProductsAggregate          generated.ProductsAggregate               "json:\"search_products_aggregate\" graphql:\"search_products_aggregate\""
	TextResult                       []*generated.TextResult                   "json:\"text_result\" graphql:\"text_result\""
	TextResultAggregate              generated.TextResultAggregate             "json:\"text_result_aggregate\" graphql:\"text_result_aggregate\""
	UserPictures                     []*generated.UserPictures                 "json:\"user_pictures\" graphql:\"user_pictures\""
	UserPicturesAggregate            generated.UserPicturesAggregate           "json:\"user_pictures_aggregate\" graphql:\"user_pictures_aggregate\""
	UserPicturesByPk                 *generated.UserPictures                   "json:\"user_pictures_by_pk\" graphql:\"user_pictures_by_pk\""
	UserProfiles                     []*generated.UserProfiles                 "json:\"user_profiles\" graphql:\"user_profiles\""
	UserProfilesAggregate            generated.UserProfilesAggregate           "json:\"user_profiles_aggregate\" graphql:\"user_profiles_aggregate\""
	UserProfilesByPk                 *generated.UserProfiles                   "json:\"user_profiles_by_pk\" graphql:\"user_profiles_by_pk\""
	Users                            []*generated.Users                        "json:\"users\" graphql:\"users\""
	UsersAggregate                   generated.UsersAggregate                  "json:\"users_aggregate\" graphql:\"users_aggregate\""
	UsersByPk                        *generated.Users                          "json:\"users_by_pk\" graphql:\"users_by_pk\""
}

type MutationRoot struct {
	DeleteAccounts                   *generated.AccountsMutationResponse               "json:\"delete_accounts\" graphql:\"delete_accounts\""
	DeleteAccountsByPk               *generated.Accounts                               "json:\"delete_accounts_by_pk\" graphql:\"delete_accounts_by_pk\""
	DeleteAttendanceConfig           *generated.AttendanceConfigMutationResponse       "json:\"delete_attendance_config\" graphql:\"delete_attendance_config\""
	DeleteAttendanceConfigByPk       *generated.AttendanceConfig                       "json:\"delete_attendance_config_by_pk\" graphql:\"delete_attendance_config_by_pk\""
	DeleteAttendanceRecords          *generated.AttendanceRecordsMutationResponse      "json:\"delete_attendance_records\" graphql:\"delete_attendance_records\""
	DeleteAttendanceRecordsByPk      *generated.AttendanceRecords                      "json:\"delete_attendance_records_by_pk\" graphql:\"delete_attendance_records_by_pk\""
	DeleteBranches                   *generated.BranchesMutationResponse               "json:\"delete_branches\" graphql:\"delete_branches\""
	DeleteBranchesByPk               *generated.Branches                               "json:\"delete_branches_by_pk\" graphql:\"delete_branches_by_pk\""
	DeleteContracts                  *generated.ContractsMutationResponse              "json:\"delete_contracts\" graphql:\"delete_contracts\""
	DeleteContractsByPk              *generated.Contracts                              "json:\"delete_contracts_by_pk\" graphql:\"delete_contracts_by_pk\""
	DeleteDistributors               *generated.DistributorsMutationResponse           "json:\"delete_distributors\" graphql:\"delete_distributors\""
	DeleteDistributorsByPk           *generated.Distributors                           "json:\"delete_distributors_by_pk\" graphql:\"delete_distributors_by_pk\""
	DeleteDistroStoreAssignments     *generated.DistroStoreAssignmentsMutationResponse "json:\"delete_distro_store_assignments\" graphql:\"delete_distro_store_assignments\""
	DeleteDistroStoreAssignmentsByPk *generated.DistroStoreAssignments                 "json:\"delete_distro_store_assignments_by_pk\" graphql:\"delete_distro_store_assignments_by_pk\""
	DeleteInventories                *generated.InventoriesMutationResponse            "json:\"delete_inventories\" graphql:\"delete_inventories\""
	DeleteInventoriesByPk            *generated.Inventories                            "json:\"delete_inventories_by_pk\" graphql:\"delete_inventories_by_pk\""
	DeleteLocations                  *generated.LocationsMutationResponse              "json:\"delete_locations\" graphql:\"delete_locations\""
	DeleteLocationsByPk              *generated.Locations                              "json:\"delete_locations_by_pk\" graphql:\"delete_locations_by_pk\""
	DeleteMarketingRegions           *generated.MarketingRegionsMutationResponse       "json:\"delete_marketing_regions\" graphql:\"delete_marketing_regions\""
	DeleteMarketingRegionsByPk       *generated.MarketingRegions                       "json:\"delete_marketing_regions_by_pk\" graphql:\"delete_marketing_regions_by_pk\""
	DeleteMateStores                 *generated.MateStoresMutationResponse             "json:\"delete_mate_stores\" graphql:\"delete_mate_stores\""
	DeleteMateStoresByPk             *generated.MateStores                             "json:\"delete_mate_stores_by_pk\" graphql:\"delete_mate_stores_by_pk\""
	DeleteProductCategories          *generated.ProductCategoriesMutationResponse      "json:\"delete_product_categories\" graphql:\"delete_product_categories\""
	DeleteProductCategoriesByPk      *generated.ProductCategories                      "json:\"delete_product_categories_by_pk\" graphql:\"delete_product_categories_by_pk\""
	DeleteProductPackagings          *generated.ProductPackagingsMutationResponse      "json:\"delete_product_packagings\" graphql:\"delete_product_packagings\""
	DeleteProductPackagingsByPk      *generated.ProductPackagings                      "json:\"delete_product_packagings_by_pk\" graphql:\"delete_product_packagings_by_pk\""
	DeleteProductPictures            *generated.ProductPicturesMutationResponse        "json:\"delete_product_pictures\" graphql:\"delete_product_pictures\""
	DeleteProductPicturesByPk        *generated.ProductPictures                        "json:\"delete_product_pictures_by_pk\" graphql:\"delete_product_pictures_by_pk\""
	DeleteProducts                   *generated.ProductsMutationResponse               "json:\"delete_products\" graphql:\"delete_products\""
	DeleteProductsByPk               *generated.Products                               "json:\"delete_products_by_pk\" graphql:\"delete_products_by_pk\""
	DeleteTextResult                 *generated.TextResultMutationResponse             "json:\"delete_text_result\" graphql:\"delete_text_result\""
	DeleteUserPictures               *generated.UserPicturesMutationResponse           "json:\"delete_user_pictures\" graphql:\"delete_user_pictures\""
	DeleteUserPicturesByPk           *generated.UserPictures                           "json:\"delete_user_pictures_by_pk\" graphql:\"delete_user_pictures_by_pk\""
	DeleteUserProfiles               *generated.UserProfilesMutationResponse           "json:\"delete_user_profiles\" graphql:\"delete_user_profiles\""
	DeleteUserProfilesByPk           *generated.UserProfiles                           "json:\"delete_user_profiles_by_pk\" graphql:\"delete_user_profiles_by_pk\""
	DeleteUsers                      *generated.UsersMutationResponse                  "json:\"delete_users\" graphql:\"delete_users\""
	DeleteUsersByPk                  *generated.Users                                  "json:\"delete_users_by_pk\" graphql:\"delete_users_by_pk\""
	InsertAccounts                   *generated.AccountsMutationResponse               "json:\"insert_accounts\" graphql:\"insert_accounts\""
	InsertAccountsOne                *generated.Accounts                               "json:\"insert_accounts_one\" graphql:\"insert_accounts_one\""
	InsertAttendanceConfig           *generated.AttendanceConfigMutationResponse       "json:\"insert_attendance_config\" graphql:\"insert_attendance_config\""
	InsertAttendanceConfigOne        *generated.AttendanceConfig                       "json:\"insert_attendance_config_one\" graphql:\"insert_attendance_config_one\""
	InsertAttendanceRecords          *generated.AttendanceRecordsMutationResponse      "json:\"insert_attendance_records\" graphql:\"insert_attendance_records\""
	InsertAttendanceRecordsOne       *generated.AttendanceRecords                      "json:\"insert_attendance_records_one\" graphql:\"insert_attendance_records_one\""
	InsertBranches                   *generated.BranchesMutationResponse               "json:\"insert_branches\" graphql:\"insert_branches\""
	InsertBranchesOne                *generated.Branches                               "json:\"insert_branches_one\" graphql:\"insert_branches_one\""
	InsertContracts                  *generated.ContractsMutationResponse              "json:\"insert_contracts\" graphql:\"insert_contracts\""
	InsertContractsOne               *generated.Contracts                              "json:\"insert_contracts_one\" graphql:\"insert_contracts_one\""
	InsertDistributors               *generated.DistributorsMutationResponse           "json:\"insert_distributors\" graphql:\"insert_distributors\""
	InsertDistributorsOne            *generated.Distributors                           "json:\"insert_distributors_one\" graphql:\"insert_distributors_one\""
	InsertDistroStoreAssignments     *generated.DistroStoreAssignmentsMutationResponse "json:\"insert_distro_store_assignments\" graphql:\"insert_distro_store_assignments\""
	InsertDistroStoreAssignmentsOne  *generated.DistroStoreAssignments                 "json:\"insert_distro_store_assignments_one\" graphql:\"insert_distro_store_assignments_one\""
	InsertInventories                *generated.InventoriesMutationResponse            "json:\"insert_inventories\" graphql:\"insert_inventories\""
	InsertInventoriesOne             *generated.Inventories                            "json:\"insert_inventories_one\" graphql:\"insert_inventories_one\""
	InsertLocations                  *generated.LocationsMutationResponse              "json:\"insert_locations\" graphql:\"insert_locations\""
	InsertLocationsOne               *generated.Locations                              "json:\"insert_locations_one\" graphql:\"insert_locations_one\""
	InsertMarketingRegions           *generated.MarketingRegionsMutationResponse       "json:\"insert_marketing_regions\" graphql:\"insert_marketing_regions\""
	InsertMarketingRegionsOne        *generated.MarketingRegions                       "json:\"insert_marketing_regions_one\" graphql:\"insert_marketing_regions_one\""
	InsertMateStores                 *generated.MateStoresMutationResponse             "json:\"insert_mate_stores\" graphql:\"insert_mate_stores\""
	InsertMateStoresOne              *generated.MateStores                             "json:\"insert_mate_stores_one\" graphql:\"insert_mate_stores_one\""
	InsertProductCategories          *generated.ProductCategoriesMutationResponse      "json:\"insert_product_categories\" graphql:\"insert_product_categories\""
	InsertProductCategoriesOne       *generated.ProductCategories                      "json:\"insert_product_categories_one\" graphql:\"insert_product_categories_one\""
	InsertProductPackagings          *generated.ProductPackagingsMutationResponse      "json:\"insert_product_packagings\" graphql:\"insert_product_packagings\""
	InsertProductPackagingsOne       *generated.ProductPackagings                      "json:\"insert_product_packagings_one\" graphql:\"insert_product_packagings_one\""
	InsertProductPictures            *generated.ProductPicturesMutationResponse        "json:\"insert_product_pictures\" graphql:\"insert_product_pictures\""
	InsertProductPicturesOne         *generated.ProductPictures                        "json:\"insert_product_pictures_one\" graphql:\"insert_product_pictures_one\""
	InsertProducts                   *generated.ProductsMutationResponse               "json:\"insert_products\" graphql:\"insert_products\""
	InsertProductsOne                *generated.Products                               "json:\"insert_products_one\" graphql:\"insert_products_one\""
	InsertTextResult                 *generated.TextResultMutationResponse             "json:\"insert_text_result\" graphql:\"insert_text_result\""
	InsertTextResultOne              *generated.TextResult                             "json:\"insert_text_result_one\" graphql:\"insert_text_result_one\""
	InsertUserPictures               *generated.UserPicturesMutationResponse           "json:\"insert_user_pictures\" graphql:\"insert_user_pictures\""
	InsertUserPicturesOne            *generated.UserPictures                           "json:\"insert_user_pictures_one\" graphql:\"insert_user_pictures_one\""
	InsertUserProfiles               *generated.UserProfilesMutationResponse           "json:\"insert_user_profiles\" graphql:\"insert_user_profiles\""
	InsertUserProfilesOne            *generated.UserProfiles                           "json:\"insert_user_profiles_one\" graphql:\"insert_user_profiles_one\""
	InsertUsers                      *generated.UsersMutationResponse                  "json:\"insert_users\" graphql:\"insert_users\""
	InsertUsersOne                   *generated.Users                                  "json:\"insert_users_one\" graphql:\"insert_users_one\""
	UpdateAccounts                   *generated.AccountsMutationResponse               "json:\"update_accounts\" graphql:\"update_accounts\""
	UpdateAccountsByPk               *generated.Accounts                               "json:\"update_accounts_by_pk\" graphql:\"update_accounts_by_pk\""
	UpdateAttendanceConfig           *generated.AttendanceConfigMutationResponse       "json:\"update_attendance_config\" graphql:\"update_attendance_config\""
	UpdateAttendanceConfigByPk       *generated.AttendanceConfig                       "json:\"update_attendance_config_by_pk\" graphql:\"update_attendance_config_by_pk\""
	UpdateAttendanceRecords          *generated.AttendanceRecordsMutationResponse      "json:\"update_attendance_records\" graphql:\"update_attendance_records\""
	UpdateAttendanceRecordsByPk      *generated.AttendanceRecords                      "json:\"update_attendance_records_by_pk\" graphql:\"update_attendance_records_by_pk\""
	UpdateBranches                   *generated.BranchesMutationResponse               "json:\"update_branches\" graphql:\"update_branches\""
	UpdateBranchesByPk               *generated.Branches                               "json:\"update_branches_by_pk\" graphql:\"update_branches_by_pk\""
	UpdateContracts                  *generated.ContractsMutationResponse              "json:\"update_contracts\" graphql:\"update_contracts\""
	UpdateContractsByPk              *generated.Contracts                              "json:\"update_contracts_by_pk\" graphql:\"update_contracts_by_pk\""
	UpdateDistributors               *generated.DistributorsMutationResponse           "json:\"update_distributors\" graphql:\"update_distributors\""
	UpdateDistributorsByPk           *generated.Distributors                           "json:\"update_distributors_by_pk\" graphql:\"update_distributors_by_pk\""
	UpdateDistroStoreAssignments     *generated.DistroStoreAssignmentsMutationResponse "json:\"update_distro_store_assignments\" graphql:\"update_distro_store_assignments\""
	UpdateDistroStoreAssignmentsByPk *generated.DistroStoreAssignments                 "json:\"update_distro_store_assignments_by_pk\" graphql:\"update_distro_store_assignments_by_pk\""
	UpdateInventories                *generated.InventoriesMutationResponse            "json:\"update_inventories\" graphql:\"update_inventories\""
	UpdateInventoriesByPk            *generated.Inventories                            "json:\"update_inventories_by_pk\" graphql:\"update_inventories_by_pk\""
	UpdateLocations                  *generated.LocationsMutationResponse              "json:\"update_locations\" graphql:\"update_locations\""
	UpdateLocationsByPk              *generated.Locations                              "json:\"update_locations_by_pk\" graphql:\"update_locations_by_pk\""
	UpdateMarketingRegions           *generated.MarketingRegionsMutationResponse       "json:\"update_marketing_regions\" graphql:\"update_marketing_regions\""
	UpdateMarketingRegionsByPk       *generated.MarketingRegions                       "json:\"update_marketing_regions_by_pk\" graphql:\"update_marketing_regions_by_pk\""
	UpdateMateStores                 *generated.MateStoresMutationResponse             "json:\"update_mate_stores\" graphql:\"update_mate_stores\""
	UpdateMateStoresByPk             *generated.MateStores                             "json:\"update_mate_stores_by_pk\" graphql:\"update_mate_stores_by_pk\""
	UpdateProductCategories          *generated.ProductCategoriesMutationResponse      "json:\"update_product_categories\" graphql:\"update_product_categories\""
	UpdateProductCategoriesByPk      *generated.ProductCategories                      "json:\"update_product_categories_by_pk\" graphql:\"update_product_categories_by_pk\""
	UpdateProductPackagings          *generated.ProductPackagingsMutationResponse      "json:\"update_product_packagings\" graphql:\"update_product_packagings\""
	UpdateProductPackagingsByPk      *generated.ProductPackagings                      "json:\"update_product_packagings_by_pk\" graphql:\"update_product_packagings_by_pk\""
	UpdateProductPictures            *generated.ProductPicturesMutationResponse        "json:\"update_product_pictures\" graphql:\"update_product_pictures\""
	UpdateProductPicturesByPk        *generated.ProductPictures                        "json:\"update_product_pictures_by_pk\" graphql:\"update_product_pictures_by_pk\""
	UpdateProducts                   *generated.ProductsMutationResponse               "json:\"update_products\" graphql:\"update_products\""
	UpdateProductsByPk               *generated.Products                               "json:\"update_products_by_pk\" graphql:\"update_products_by_pk\""
	UpdateTextResult                 *generated.TextResultMutationResponse             "json:\"update_text_result\" graphql:\"update_text_result\""
	UpdateUserPictures               *generated.UserPicturesMutationResponse           "json:\"update_user_pictures\" graphql:\"update_user_pictures\""
	UpdateUserPicturesByPk           *generated.UserPictures                           "json:\"update_user_pictures_by_pk\" graphql:\"update_user_pictures_by_pk\""
	UpdateUserProfiles               *generated.UserProfilesMutationResponse           "json:\"update_user_profiles\" graphql:\"update_user_profiles\""
	UpdateUserProfilesByPk           *generated.UserProfiles                           "json:\"update_user_profiles_by_pk\" graphql:\"update_user_profiles_by_pk\""
	UpdateUsers                      *generated.UsersMutationResponse                  "json:\"update_users\" graphql:\"update_users\""
	UpdateUsersByPk                  *generated.Users                                  "json:\"update_users_by_pk\" graphql:\"update_users_by_pk\""
}
type BulkInsertAccounts struct {
	InsertAccounts *struct {
		Returning []*struct {
			UserID string "json:\"user_id\" graphql:\"user_id\""
		} "json:\"returning\" graphql:\"returning\""
	} "json:\"insert_accounts\" graphql:\"insert_accounts\""
}
type UpsertUser struct {
	InsertUsersOne *struct {
		ID string "json:\"id\" graphql:\"id\""
	} "json:\"insert_users_one\" graphql:\"insert_users_one\""
}
type UpsertUserProfile struct {
	InsertUserProfilesOne *struct {
		ID string "json:\"id\" graphql:\"id\""
	} "json:\"insert_user_profiles_one\" graphql:\"insert_user_profiles_one\""
}
type GetAccount struct {
	Accounts []*struct {
		UserID    string  "json:\"user_id\" graphql:\"user_id\""
		Email     string  "json:\"email\" graphql:\"email\""
		Role      string  "json:\"role\" graphql:\"role\""
		LastLogin *string "json:\"last_login\" graphql:\"last_login\""
		User      *struct {
			ID           string  "json:\"id\" graphql:\"id\""
			Address      string  "json:\"address\" graphql:\"address\""
			BirthDate    string  "json:\"birth_date\" graphql:\"birth_date\""
			GovernmentID string  "json:\"government_id\" graphql:\"government_id\""
			ContractID   *string "json:\"contract_id\" graphql:\"contract_id\""
			Locked       *bool   "json:\"locked\" graphql:\"locked\""
			Name         string  "json:\"name\" graphql:\"name\""
			ProfileID    *string "json:\"profile_id\" graphql:\"profile_id\""
			CreatedAt    *string "json:\"created_at\" graphql:\"created_at\""
			LastModified *string "json:\"last_modified\" graphql:\"last_modified\""
		} "json:\"user\" graphql:\"user\""
	} "json:\"accounts\" graphql:\"accounts\""
}
type ListAccount struct {
	Accounts []*struct {
		UserID    string  "json:\"user_id\" graphql:\"user_id\""
		Email     string  "json:\"email\" graphql:\"email\""
		Role      string  "json:\"role\" graphql:\"role\""
		LastLogin *string "json:\"last_login\" graphql:\"last_login\""
		User      *struct {
			ID           string  "json:\"id\" graphql:\"id\""
			Address      string  "json:\"address\" graphql:\"address\""
			BirthDate    string  "json:\"birth_date\" graphql:\"birth_date\""
			GovernmentID string  "json:\"government_id\" graphql:\"government_id\""
			ContractID   *string "json:\"contract_id\" graphql:\"contract_id\""
			Locked       *bool   "json:\"locked\" graphql:\"locked\""
			Name         string  "json:\"name\" graphql:\"name\""
			ProfileID    *string "json:\"profile_id\" graphql:\"profile_id\""
			CreatedAt    *string "json:\"created_at\" graphql:\"created_at\""
			LastModified *string "json:\"last_modified\" graphql:\"last_modified\""
		} "json:\"user\" graphql:\"user\""
	} "json:\"accounts\" graphql:\"accounts\""
}
type GetMarketingRegions struct {
	MarketingRegions []*struct {
		Notes      string "json:\"notes\" graphql:\"notes\""
		RegionCode string "json:\"region_code\" graphql:\"region_code\""
		ID         string "json:\"id\" graphql:\"id\""
	} "json:\"marketing_regions\" graphql:\"marketing_regions\""
}

const BulkInsertAccountsQuery = `mutation bulkInsertAccounts ($accountsInsertData: [accounts_insert_input!]!) {
	insert_accounts(objects: $accountsInsertData, on_conflict: {constraint:accounts_email_key,update_columns:[email]}) {
		returning {
			user_id
		}
	}
}
`

func (c *Client) BulkInsertAccounts(ctx context.Context, accountsInsertData []*generated.AccountsInsertInput, httpRequestOptions ...client.HTTPRequestOption) (*BulkInsertAccounts, error) {
	vars := map[string]interface{}{
		"accountsInsertData": accountsInsertData,
	}

	var res BulkInsertAccounts
	if err := c.Client.Post(ctx, BulkInsertAccountsQuery, &res, vars, httpRequestOptions...); err != nil {
		return nil, err
	}

	return &res, nil
}

const UpsertUserQuery = `mutation upsertUser ($accountId: uuid!, $address: String!, $governmentId: String!, $birthDate: date!, $name: String!) {
	insert_users_one(object: {account_id:$accountId,address:$address,government_id:$governmentId,birth_date:$birthDate,name:$name}, on_conflict: {constraint:users_government_id_key,update_columns:[last_modified]}) {
		id
	}
}
`

func (c *Client) UpsertUser(ctx context.Context, accountID string, address string, governmentID string, birthDate string, name string, httpRequestOptions ...client.HTTPRequestOption) (*UpsertUser, error) {
	vars := map[string]interface{}{
		"accountId":    accountID,
		"address":      address,
		"governmentId": governmentID,
		"birthDate":    birthDate,
		"name":         name,
	}

	var res UpsertUser
	if err := c.Client.Post(ctx, UpsertUserQuery, &res, vars, httpRequestOptions...); err != nil {
		return nil, err
	}

	return &res, nil
}

const UpsertUserProfileQuery = `mutation upsertUserProfile ($userId: uuid!, $devices: jsonb!) {
	insert_user_profiles_one(object: {user_id:$userId,devices:$devices}, on_conflict: {constraint:user_profiles_user_id_key,update_columns:[]}) {
		id
	}
}
`

func (c *Client) UpsertUserProfile(ctx context.Context, userID string, devices string, httpRequestOptions ...client.HTTPRequestOption) (*UpsertUserProfile, error) {
	vars := map[string]interface{}{
		"userId":  userID,
		"devices": devices,
	}

	var res UpsertUserProfile
	if err := c.Client.Post(ctx, UpsertUserProfileQuery, &res, vars, httpRequestOptions...); err != nil {
		return nil, err
	}

	return &res, nil
}

const GetAccountQuery = `query getAccount ($id: uuid!) {
	accounts(where: {user_id:{_eq:$id}}) {
		user_id
		email
		role
		last_login
		user {
			id
			address
			birth_date
			government_id
			contract_id
			locked
			name
			profile_id
			created_at
			last_modified
		}
	}
}
`

func (c *Client) GetAccount(ctx context.Context, id string, httpRequestOptions ...client.HTTPRequestOption) (*GetAccount, error) {
	vars := map[string]interface{}{
		"id": id,
	}

	var res GetAccount
	if err := c.Client.Post(ctx, GetAccountQuery, &res, vars, httpRequestOptions...); err != nil {
		return nil, err
	}

	return &res, nil
}

const ListAccountQuery = `query listAccount ($last_login: timestamptz!) {
	accounts(where: {last_login:{_gt:$last_login}}, limit: 10) {
		user_id
		email
		role
		last_login
		user {
			id
			address
			birth_date
			government_id
			contract_id
			locked
			name
			profile_id
			created_at
			last_modified
		}
	}
}
`

func (c *Client) ListAccount(ctx context.Context, lastLogin string, httpRequestOptions ...client.HTTPRequestOption) (*ListAccount, error) {
	vars := map[string]interface{}{
		"last_login": lastLogin,
	}

	var res ListAccount
	if err := c.Client.Post(ctx, ListAccountQuery, &res, vars, httpRequestOptions...); err != nil {
		return nil, err
	}

	return &res, nil
}

const GetMarketingRegionsQuery = `query getMarketingRegions ($id: uuid!) {
	marketing_regions(where: {id:{_eq:$id}}) {
		notes
		region_code
		id
	}
}
`

func (c *Client) GetMarketingRegions(ctx context.Context, id string, httpRequestOptions ...client.HTTPRequestOption) (*GetMarketingRegions, error) {
	vars := map[string]interface{}{
		"id": id,
	}

	var res GetMarketingRegions
	if err := c.Client.Post(ctx, GetMarketingRegionsQuery, &res, vars, httpRequestOptions...); err != nil {
		return nil, err
	}

	return &res, nil
}
